name: Gradle Build

on:
  push:
    branches-ignore:
      - main
      - master
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '11'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Ubuntu
      id: ubuntu-bootstrap
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y -qq install haveged
        sudo systemctl -q enable haveged
        sudo systemctl -q restart haveged
        echo "::set-output name=today::$(/bin/date -u "+%Y%m%d")"
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        gradle-home-cache-excludes: dependency-check-data
    - name: OWASP dependency-check-data cache
      uses: actions/cache@v3
      with:
        path: ~/.gradle/dependency-check-data
        key: ${{ runner.os }}-dependency-check-data-${{ steps.ubuntu-bootstrap.outputs.today }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-data-
    - name: Execute Gradle build
      run: |
        ./gradlew check
    - name: Gradle Dependency Check Analyze
      run: |
        ./gradlew dependencyCheckAnalyze
    - name: codecov.io
      uses: codecov/codecov-action@v3.1.0
    - name: Gradle Build Reports
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          **/build/reports
