name: Gradle Build

on:
  push:
    branches:
      - develop
  pull_request:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '11'
        components: 'js'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Ubuntu
      id: ubuntu-bootstrap
      run: |
        sudo apt-get -y -qq update
        sudo apt-get -y -qq install haveged
        sudo systemctl -q enable haveged --now
        echo "today=$(/bin/date -u '+%Y%m%d')" >> $GITHUB_OUTPUT
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        gradle-home-cache-excludes: dependency-check-data
    - name: OWASP dependency-check-data cache
      uses: actions/cache@v3
      with:
        path: ~/.gradle/dependency-check-data
        key: ${{ runner.os }}-dependency-check-data-${{ steps.ubuntu-bootstrap.outputs.today }}
        restore-keys: |
          ${{ runner.os }}-dependency-check-data-
    - name: Execute Gradle build
      env:
        JDK_JAVA_OPTIONS: -Dpolyglot.engine.WarnInterpreterOnly=false
      run: |
        ./gradlew check
    - name: Gradle Dependency Check Analyze
      run: |
        ./gradlew dependencyCheckAnalyze
    - name: codecov.io
      uses: codecov/codecov-action@v3.1.1
    - name: Gradle Build Reports
      uses: actions/upload-artifact@v3
      with:
        name: build-reports
        path: |
          **/build/reports

  dependabot-merge:
    needs: build
    permissions:
      contents: write
      pull-requests: write
    if: |
      github.actor == 'dependabot[bot]'
    runs-on: ubuntu-latest
    steps:
    - name: Find associated PR
      uses: jwalton/gh-find-current-pr@v1
      id: findpr
      with:
        github-token: ${{ github.token }}
        state: open
        sha: ${{ github.event.pull_request.head.sha || github.event.workflow_run.head_sha || github.sha }}
    - name: dependabot metadata
      id: depbot-metadata
      uses: dependabot/fetch-metadata@v1
      continue-on-error: true
    - name: merge-if-built
      uses: fastify/github-action-merge-dependabot@v3
      continue-on-error: true
      if: ${{steps.depbot-metadata.outputs.update-type == 'version-update:semver-patch'}}
      with:
        pr-number: ${{ steps.findpr.outputs.pr }}
        target: patch