name: Gradle Dependency Submission

on:
  push:
    branches:
      - develop

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
      with:
        fetch-depth: 0
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '11'
        components: 'js'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Gradle
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        gradle-home-cache-excludes: dependency-check-data
    - name: gradle-dependency-submission
      uses: mikepenz/gradle-dependency-submission@v0.8.4
      with:
        use-gradlew: true
        gradle-build-module: |-
          :
        gradle-build-configuration: |-
          compileClasspath
      env:
        JDK_JAVA_OPTIONS: -Dpolyglot.engine.WarnInterpreterOnly=false