name: publish-snapshot

on:
  push:
    branches-ignore:
      - main
      - master

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Set up GraalVM
      uses: graalvm/setup-graalvm@v1
      with:
        version: 'latest'
        java-version: '11'
        github-token: ${{ secrets.GITHUB_TOKEN }}
    - name: Setup Ubuntu
      run: |
        sudo apt-get -y update
        sudo apt-get -y install haveged
        sudo systemctl enable haveged
        sudo systemctl restart haveged
    - name: Gradle Build
      uses: gradle/gradle-build-action@v2
      with:
        gradle-version: wrapper
        arguments: -Djava.security.egd=file:/dev/./urandom publish
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}